# Generated by Django 4.2.6 on 2023-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='clientes',
            name='Apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='DV',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='RUT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Correo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
