# Generated by Django 4.2.6 on 2023-11-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_proveedor_clientes_apellido_clientes_dv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='RUT',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
