# Generated by Django 4.2.6 on 2023-11-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_clientes_rut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
