# Generated by Django 4.2.6 on 2023-11-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_delete_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=11, null=True)),
                ('DV', models.CharField(max_length=1, null=True)),
                ('Nombre', models.CharField(max_length=255, null=True)),
                ('Apellido', models.CharField(max_length=255, null=True)),
                ('Direccion', models.CharField(max_length=255, null=True)),
                ('Telefono', models.CharField(max_length=20, null=True)),
                ('Correo', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
