# Generated by Django 4.2.6 on 2023-11-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
