# Generated by Django 4.2.6 on 2023-11-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_clientes_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='DV',
        ),
    ]
