# Generated by Django 4.2.6 on 2023-11-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='RUT',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
