# Generated by Django 4.2.6 on 2023-11-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='RUT',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
