# Generated by Django 5.0.6 on 2024-05-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_segmento_tipoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='SegmentoProducto',
        ),
        migrations.DeleteModel(
            name='Segmento',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
