# Generated by Django 5.0.6 on 2024-05-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_tipoproducto_segmentoproducto_delete_segmento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMarca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Segmentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSegmento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTienda', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoProducto', models.CharField(max_length=255)),
                ('SegmentoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.segmentos')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosIndividuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=255)),
                ('nombreProducto', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.marcas')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tipoproductos')),
            ],
        ),
    ]
