# Generated by Django 5.0.6 on 2024-05-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosindividuales',
            name='valorProducto',
            field=models.IntegerField(null=True),
        ),
    ]
