# Generated by Django 5.0.6 on 2024-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_productosindividuales_valorproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
