# Generated by Django 5.0.6 on 2024-05-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_productosindividuales_codigoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='tienda',
        ),
        migrations.DeleteModel(
            name='Tiendas',
        ),
    ]
