# Generated by Django 5.0.6 on 2024-05-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_carrocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_CarroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=255)),
                ('nombreProducto', models.CharField(max_length=255)),
                ('valorCLP', models.IntegerField(null=True)),
                ('valorCLP_string', models.CharField(default='Nulo', max_length=255)),
                ('valorUSD', models.IntegerField(null=True)),
                ('valorUSD_string', models.CharField(default='Nulo', max_length=255)),
                ('marca', models.CharField(max_length=50)),
                ('tipoProducto', models.CharField(max_length=255)),
                ('NombreSegmento', models.CharField(default='Sin Segmento', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CarroCompra',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto_carrocompra'),
        ),
    ]
