# Generated by Django 5.0.6 on 2024-05-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productovista_valorclp_string'),
        ('store', '0027_carrito_producto_carrocompra_delete_carrocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productovista'),
        ),
        migrations.DeleteModel(
            name='Producto_CarroCompra',
        ),
    ]
