# Generated by Django 5.0.6 on 2024-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_carrito_producto_delete_producto_carrocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscripcionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CorreoSubscipcion', models.EmailField(max_length=254, unique=True)),
                ('FechaSubscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
