# Generated by Django 5.0.6 on 2024-07-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_subscripcionsemanal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carrito'},
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name': 'Marcas', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='productosindividuales',
            options={'verbose_name': 'ProductosIndividuales', 'verbose_name_plural': 'ProductosIndividuales'},
        ),
        migrations.AlterModelOptions(
            name='segmentos',
            options={'verbose_name': 'Segmentos', 'verbose_name_plural': 'Segmentos'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='subscripcionsemanal',
            options={'verbose_name': 'CorreosSuscritos', 'verbose_name_plural': 'CorreosSuscritos'},
        ),
        migrations.AlterModelOptions(
            name='tipoproductos',
            options={'verbose_name': 'TipoProductos', 'verbose_name_plural': 'TipoProductos'},
        ),
    ]
