# Generated by Django 5.0.6 on 2024-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=255)),
                ('nombreProducto', models.CharField(max_length=255)),
                ('valorCLP', models.IntegerField(null=True)),
                ('marca', models.CharField(max_length=50)),
                ('tipoProducto', models.CharField(max_length=255)),
                ('stockDisponible', models.IntegerField(default=0)),
            ],
        ),
    ]
