# Generated by Django 5.0.6 on 2024-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovista',
            name='NombreSegmento',
            field=models.CharField(default='Sin Segmento', max_length=255),
        ),
    ]
