# Generated by Django 5.0.6 on 2024-05-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productovista_nombresegmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovista',
            name='valorCLP_string',
            field=models.CharField(default='Nulo', max_length=255),
            preserve_default=False,
        ),
    ]
